# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 077727ce54417aab6b182869db93fe1439c3ca152f82ec23b47b4202481dab8165c46a7fad5f128d44fe4634a171f7c6f4b7e967814afcaabec36456c348ac95

test:
  secret_key_base: de5b93adc656c819ae23c54066634299624cca1c6dacda31c7a22630d33031d9763a7f76ad24a0459eba5f6f01cf0faad74d1b52c63044a2d71fe14d92f58517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
